### ISSUE TITLE
Explanation of JShelter recommendation

### ISSUE THREAD

**Issue by hardcore-sushi** [melo936/ChromiumHardening#21]
Hi,

On the extensions page, you recommend JShelter but not when using Brave or Ungoogled Chromium. Can you explain why? And how do you determine if this extension should be used with other browsers?

Thanks

**Comment by dreammjow** [comment]
Hello @hardcore-sushi,

Brave and Ungoogled-Chromium browsers have their own fingerprinting protections, which don't rely on extensions. By using any fingerprint protection extension will possibly cause leakage as mentioned on the extensions page, security and performance issues.

**Comment by hardcore-sushi** [comment]
OK, thanks for this explanation. Maybe you could add it in the extensions page in case future readers have the same question.
